### ISSUE TITLE
Doesnt make the first call when user scrolls down and goes back up

### ISSUE THREAD

**Issue by jasonpraful** [vdmrgv/react-easy-infinite-scroll-hook#4]
**Describe the bug**
When the user reaches either the top/bottom of the div the hook doesn't call next if it has already made a call before. 

**Screenshots**

![image](https://user-images.githubusercontent.com/32552408/178154244-0bb73a47-30db-47c9-9360-ffe45079e9c3.png)
![image](https://user-images.githubusercontent.com/32552408/178154222-359bbe25-f6eb-4845-b0b2-ee15a7092711.png)

**Additional context**

**Comment by vdmrgv** [comment]
Hey @jasonpraful !
I tested it and it works fine in my environment, you can try it [here](https://codesandbox.io/s/react-easy-infinite-scroll-hook-6w9szb).
Could you check  [this](https://codesandbox.io/s/react-easy-infinite-scroll-hook-6w9szb) example and if it doesn't work, please attach the code snippet and I will try to help you!

**Comment by jasonpraful** [comment]
Doesn't seem to work :/ I noticed another potential bug, I am not able to access the updated state data from my parent element. Happy to go through the code with you - just added you on twitter 😁 

```typescript
// Get Direction Function
  const getDirection = async (direction: ScrollDirection) => {
    if (direction === 'up') {
      const query = `/api/chats?channelId=${chatChannel?._id}`
      const firstMessage = messages[0]._id
      prevUpMessageId = firstMessage
      fetchMessages(`${query}&beforeId=${firstMessage}`)
    } else if (direction === 'down') {
      const lastMessage = messages[messages.length - 1]._id
    }
  }
```

```typescript
// Init
 const { setRef } = useInfiniteScroll({
    next: getDirection,
    rowCount: 20,
    initialScroll: { top: 1143, left: 0 },
    hasMore: { up: true, down: true }
  })
```

```typescript
// Component
 <div style={{
          height: '75%',
          marginTop: 5,
          display: 'flex',
          flexDirection: 'column-reverse'
        }}
      >
        <div
          ref={setRef}
          style={{
            overflowY: 'auto'
          }}
        >
 {messages.map((message) => (
            <div style={{ height: 'auto' }} key={message._id}>
              <Message />
            </div>
          ))}
        </div>
```


```typescript
// Fetch Function
  const fetchMessages = async (query: string) => {
    const retrievedmessages = await axios.get(query))
  
    if (retrievedmessages.data.data.length > 0) {
      const { data } = retrievedmessages.data
      setMessages((messages) => [...data, ...messages])
    } 
  }
```

**Comment by vdmrgv** [comment]
> Doesn't seem to work :/ I noticed another potential bug, I am not able to access the updated state data from my parent element. Happy to go through the code with you - just added you on twitter 😁
> 
> ```ts
> // Get Direction Function
>   const getDirection = async (direction: ScrollDirection) => {
>     if (direction === 'up') {
>       const query = `/api/chats?channelId=${chatChannel?._id}`
>       const firstMessage = messages[0]._id
>       prevUpMessageId = firstMessage
>       fetchMessages(`${query}&beforeId=${firstMessage}`)
>     } else if (direction === 'down') {
>       const lastMessage = messages[messages.length - 1]._id
>     }
>   }
> ```
> 
> ```ts
> // Init
>  const { setRef } = useInfiniteScroll({
>     next: getDirection,
>     rowCount: messages.length,
>     initialScroll: { top: 1143, left: 0 },
>     hasMore: { up: true, down: true }
>   })
> ```
> 
> ```ts
> // Component
>  <div style={{
>           height: '75%',
>           marginTop: 5,
>           display: 'flex',
>           flexDirection: 'column-reverse'
>         }}
>       >
>         <div
>           ref={setRef}
>           style={{
>             overflowY: 'auto'
>           }}
>         >
>  {messages.map((message) => (
>             <div style={{ height: 'auto' }} key={message._id}>
>               <Message />
>             </div>
>           ))}
>         </div>
> ```
> 
> ```ts
> // Fetch Function
>   const fetchMessages = async (query: string) => {
>     const retrievedmessages = await axios.get(query))
>   
>     if (retrievedmessages.data.data.length > 0) {
>       const { data } = retrievedmessages.data
>       setMessages((messages) => [...data, ...messages])
>     } 
>   }
> ```

thanks, I'll take a look today

**Comment by vdmrgv** [comment]
I found the cause of the bug, working on a fix 🙂
I'll push it today

**Comment by vdmrgv** [comment]
@jasonpraful I fixed the issue and published a new version so you can try it. Let me know if I'm wrong 😎
