### ISSUE TITLE
Add support for react-window

### ISSUE THREAD

**Issue by ejdzipi** [vdmrgv/react-easy-infinite-scroll-hook#75]
It would be nice, if you could add support for [react-window](https://github.com/bvaughn/react-window) virtualization library. It's slightly more modern alternative for react-virtualized, from the same author. Currently, I only get console error:
`Sorry I can't use this container - try using a different DOM element.`

Would it be possible to add support? 
Thanks.

**Comment by vdmrgv** [comment]
> It would be nice, if you could add support for [react-window](https://github.com/bvaughn/react-window) virtualization library. It's slightly more modern alternative for react-virtualized, from the same author. Currently, I only get console error: `Sorry I can't use this container - try using a different DOM element.`
> 
> Would it be possible to add support? Thanks.

Hi @ejdzipi! Yes it's possible, but you can use it with `react-window` library right now. Just pass the correct `node` to `react-easy-infinite-scroll-hook` ref like this:
```
  ...

  const ref = useInfiniteScroll({
      next,
      rowCount: data.length,
      hasMore,
  });

  const setRef = useCallback((node) => {
      if(node)
        ref.current=node._outerRef
  }, [])

 return (
      <FixedSizeList
        ref={setRef}
        className="List"
        width={600}
        height={500}
        itemSize={60}
        itemCount={data.length}
      >
        {Row}
      </FixedSizeList>
)
```

I think I'll add this directly to the hook in future releases.

**Comment by ejdzipi** [comment]
Thanks for quick reply! 💯
