### ISSUE TITLE
Infinite loading breaks when scrollbar is dragged

### ISSUE THREAD

**Issue by ejdzipi** [vdmrgv/react-easy-infinite-scroll-hook#81]
Infinite loading breaks when scrollbar is dragged to the end. It will not load more rows, even after scroll is changed. This bug happens in all examples, but it is most easy to capture in example with prepending items.

![Animation](https://user-images.githubusercontent.com/32513027/206200429-9ea23c98-6c6c-468e-8795-7bb7b5bb2235.gif)

 - OS: Windows 10
 - Browser: Chrome
 - Version: 108.0.5359.95 (64bit)

**Comment by vdmrgv** [comment]
Hi @ejdzipi 
Thanks for report. I'll take a look on it later

**Comment by vdmrgv** [comment]
Hey, @ejdzipi , I just fixed this bug. It should now work correctly when dragging the scrollbar
