### ISSUE TITLE
If initial viewport is not scrollable, next function wouldnt be triggered 

### ISSUE THREAD

**Issue by damirdjukanovic** [vdmrgv/react-easy-infinite-scroll-hook#98]
I have an api that I fetch exactly 7 items per request, and if the container is not overflowing (the scrollbar isn't present) the next function would not be called. I tried setting the scrollThreshold to 0px and it does work to some degree, but this is not a solution I would like to use. However, when I reduce the viewport width (ex. I resize the window), I would get a scrollbar and the next function would be called as expected. Am I missing something ?

**Comment by vdmrgv** [comment]
Hi @damirdjukanovic! In the current implementation, the `next` function is called using the `scroll` event in your container, which is called when scrolling the scroll bar or another possible method that triggers this event. As a solution to this problem, you can increase the number of items received in the `fetch` function to make the container scrollable.
